### PR TITLE
Typ1: Tidey config

### PR DESCRIPTION
**Pull request by dfessor**
and removing according lines in Typ1

### CODE REVIEW

**Comment by dfessor** [comment]
and wrapped a function around the import (still not sure about the global variables)

**Comment by dfessor** [comment]
no global variables in Typ1 and FC
I noticed though, that the Window doesn't start up as fast as it previously did.

**Comment by dfessor** [comment]
It seems Klassen was needed after all

**Comment by chrisiweb** [comment]
Yes Klassen is needed, but it's a dictionary now. Please keep it in the config file

**Pull request merged**
