### PR TITLE
Create pdf via py

### PR DESCRIPTION
**Pull request by dfessor**
Seems to work in Linux, although without clickable pdf
@chrisiweb : can you check if it works with Windows?

Sidenotes: 
- many `open()`-functions need `open(file, encoding='ISO-8859-1')` for it to work in Linux
- `'__file__'` instead of `__file__` was a big issue, because it hindered me to open the script from a different location (e.g. `python3 ./dir1/dir2/Aufgabensammlung (inoffiziell)/Typ 1 Aufgaben/Typ1 LaTeX file assistent 4.0.py`)

### CODE REVIEW

**Comment by chrisiweb** [comment]
Doesn't work with windows. There is an error with: "subprocess.Popen('Teildokument.pdf',cwd=working_path).poll()" - there might be a way of handling with that.
Unfortunately the PDF is not clickable anymore on Windows either - which absolutely has to work!

**Comment by dfessor** [comment]
All seems to work now. My commits should state sufficiently what i did. Please test an tell me if it works on windows.

**Comment by dfessor** [comment]
Works like a charm! (Except for the clickable pdf)

**Comment by chrisiweb** [comment]
@dfessor: Every example in the pdf should be clickable, and when clicked open the LaTeX source code of this example. It works on windows now! (The problem might be the PDF-Reader your are using, not linux)

**Pull request merged**
