### PR TITLE
fix_singledot

### PR DESCRIPTION
**Pull request by dfessor**
path in Teildokument.tex must have two dots in order for latex to find
the files.
Does it still work with windows?

If not we have two choices:
a) let latex compile in root folder (which means it would generate the pdf in root too)
b) fork for systems with if

PS: Dots were appended in lines `1661` and `1664` as `'\input{".'+value+'"`

### CODE REVIEW

**Comment by chrisiweb** [comment]
Hm, ok very weired. I did not change this since several updates (since the
change from relative to absolute paths). It does not work on Windows, and I
am quite sure it used to work on Mac. The variable "value" in line 1661 and
1664 is supposed to be an absolute Path. In Windows the path now looks
like: ".C:/Users/..."
Are you sure you updated the log_files before?

Am Sa., 20. Apr. 2019 um 15:11 Uhr schrieb dfessor <notifications@github.com

**Comment by dfessor** [comment]
On Linux the path is `../_database/Typ1Aufgaben/...`.
The double dot lets latex jump up one level, since it is executed in `./Teildokumente/` (line1363).
If I'd there was a single dot latex would look for the directory `_database` in `Teildokumente`.

Yes, I refreshed the database (if that's what you mean with log_file).

**Comment by dfessor** [comment]
creating the pdf works with linux now. please check if it still works with windows.
It should however, because I only changed in an if statement for linux/mac

**Comment by chrisiweb** [comment]
LaMA does not need changes for Mac. PyQt branch was adapted as suggested to make it working for Linux.

**Pull request closed without merging**
